# Generated by Django 2.1.5 on 2019-01-28 11:46

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_name', models.CharField(max_length=100, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('todo_desc', models.TextField(default='', verbose_name='Description')),
                ('created_date', models.DateField(default=datetime.date(2019, 1, 28), verbose_name='Created Date')),
                ('updated_date', models.DateField(default=datetime.date(2019, 1, 28), verbose_name='Updated Date')),
                ('todo_status', models.BooleanField(default=False, verbose_name='Completed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
