# Generated by Django 2.1.5 on 2019-01-28 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20190128_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_desc',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_date',
            field=models.DateField(default=datetime.date(2019, 1, 28), verbose_name='Updated Date'),
        ),
    ]
